"""Initial revision

Revision ID: 52254e3d2f1b
Revises: 
Create Date: 2024-11-23 22:28:40.907351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '52254e3d2f1b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('categories', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('categories', 'category_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.add_column('customers', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('customers', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('customers', 'first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('customers', 'last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('customers', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('customers', 'registration_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_unique_constraint(None, 'customers', ['email'])
    op.add_column('discounts', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('discounts', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('discounts', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('discounts', 'discount_percent',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
    op.alter_column('discounts', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('discounts', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('order_items', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('order_items', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('order_items', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order_items', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order_items', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.add_column('order_statuses', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('order_statuses', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('order_statuses', 'status_description',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.add_column('orders', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('orders', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('orders', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('orders', 'order_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('orders', 'total_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('orders', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('payments', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('payments', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('payments', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('payments', 'payment_method',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('payments', 'payment_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('payments', 'payment_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('products', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('products', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('products', 'product_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('products', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.add_column('reviews', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('reviews', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('reviews', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reviews', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reviews', 'rating',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reviews', 'review_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('shipping', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('shipping', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('shipping', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('shipping', 'shipping_address',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('shipping', 'shipping_method',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('shipping', 'shipping_cost',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('shipping', 'shipping_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('shipping', 'shipping_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.add_column('storage', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('storage', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('storage', 'storage_address',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('storage', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('storage', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('storage', 'storage_address',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.drop_column('storage', 'updated_at')
    op.drop_column('storage', 'created_at')
    op.alter_column('shipping', 'shipping_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('shipping', 'shipping_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('shipping', 'shipping_cost',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('shipping', 'shipping_method',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('shipping', 'shipping_address',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('shipping', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('shipping', 'updated_at')
    op.drop_column('shipping', 'created_at')
    op.alter_column('reviews', 'review_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('reviews', 'rating',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reviews', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reviews', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('reviews', 'updated_at')
    op.drop_column('reviews', 'created_at')
    op.alter_column('products', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('products', 'product_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'created_at')
    op.alter_column('payments', 'payment_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('payments', 'payment_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('payments', 'payment_method',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('payments', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('payments', 'updated_at')
    op.drop_column('payments', 'created_at')
    op.alter_column('orders', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('orders', 'total_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('orders', 'order_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('orders', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('orders', 'updated_at')
    op.drop_column('orders', 'created_at')
    op.alter_column('order_statuses', 'status_description',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('order_statuses', 'updated_at')
    op.drop_column('order_statuses', 'created_at')
    op.alter_column('order_items', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('order_items', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('order_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('order_items', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('order_items', 'updated_at')
    op.drop_column('order_items', 'created_at')
    op.alter_column('discounts', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('discounts', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('discounts', 'discount_percent',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    op.alter_column('discounts', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('discounts', 'updated_at')
    op.drop_column('discounts', 'created_at')
    op.drop_constraint(None, 'customers', type_='unique')
    op.alter_column('customers', 'registration_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('customers', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('customers', 'last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('customers', 'first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('customers', 'updated_at')
    op.drop_column('customers', 'created_at')
    op.alter_column('categories', 'category_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('categories', 'updated_at')
    op.drop_column('categories', 'created_at')
    # ### end Alembic commands ###
